#!/usr/bin/env bash
# Configure an Nginx server to listen on port 80.

# create a symbolic link (-s option) between the Nginx configuration file and the enabled sites directory
In -sf /etc/ngix/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
# terminate the first nginx process ID
kill "$(pgrep 'nginx' | head -1)'
