#!/usr/bin/env bash
# running as nginx user
sudo sed -1 's/user www-data/user nginx' /etc/nginx/nginx.conf
sudo sed -1 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
